### ISSUE TITLE
Gracefully handle analytics offline

### ISSUE THREAD

**Issue by collinjackson** [nexus-xyz/network-api#27]
```
thread 'main' panicked at src/prover.rs:154:66:
called Result::unwrap() on an Err value: Protocol(ResetWithoutClosingHandshake)
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/analytics.rs:52:14:
called Result::unwrap() on an Err value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.mixpanel.com")), port: None, path: "/track", query: Some("ip=1"), fragment: None }, source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", Custom { kind: Interrupted, error: JoinError::Cancelled(Id(169)) })) }
```

**Comment by collinjackson** [comment]
This appears to be working now! Probably fixed in https://github.com/nexus-xyz/network-api/pull/36

Thanks @dprats
